[theme]

# Primary accent for interactive elements
primaryColor = '#d33682'

# Background color for the main content area
#backgroundColor = '#002b36'
backgroundColor = "#00172B"

# Background color for sidebar and most interactive widgets
#secondaryBackgroundColor = '#586e75'
secondaryBackgroundColor = "#000"

# Color used for almost all text
#textColor = '#fafafa'
textColor = "#C6CDD4"

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "monospace"
